[tool.pytest.ini_options]
pythonpath = "src"
cache_dir = "/dev/null"
console_output_style = "progress-even-when-capture-no"
addopts = [
    "-s",
    "-vvv",
    "-p no:cacheprovider",
    "--cache-clear",
    "--import-mode=importlib",
    "--log-cli-level=INFO"
]
log_cli_level = "INFO"
testpaths = ["tests"]