[tool.pytest.ini_options]
pythonpath = "src"
cache_dir = "/dev/null"
console_output_style = "progress-even-when-capture-no"
addopts = [
    "-s",
    "-vvv",
    "-p no:cacheprovider",
    "--cache-clear",
    # benchmark flags
    "--benchmark-enable",
    "--benchmark-verbose",
    "--benchmark-storage=file://.reports/benchmarks/",
    "--benchmark-histogram=.reports/benchmarks/hist",
    "--benchmark-cprofile-dump=.reports/benchmarks/cprofile",
    "--benchmark-json=.reports/benchmarks/latest_benchmark.json",
    "--benchmark-save-data",
    "--benchmark-name=long",
    "--benchmark-cprofile=cumtime_per",
    "--benchmark-save=benchmark",
    "--benchmark-sort=max",
    "--benchmark-calibration-precision=20",
    "--benchmark-warmup=on",
    "--benchmark-warmup-iterations=5",
    "--benchmark-min-time=0.000000001",
    "--benchmark-autosave",
    "--benchmark-cprofile-loops=20"
]
asyncio_mode = "strict"
asyncio_default_fixture_loop_scope = "function"
log_cli_level = "INFO"
log_cli = true
testpaths = ["tests"]
